### ISSUE TITLE
Update test on tutorials

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-tutorials#197]
This should be done once this PR https://github.com/deepset-ai/haystack/pull/5028 is merged and we have base images with every release.

* Add metadata to each tutorial to set on which image it should be tested
* Run nightly test on these versions
* Run nightly tests on main as well to be cautious about upcoming changes
* Release images should be used when a tutorial is created or updated (on PRs)

Any other ideas @silvanocerza?

**Comment by bilgeyucel** [comment]
Our decision after our sync
- PRs: latest version & pinned versions (not main)
- Nightly: latest version & pinned versions + main

**Comment by bilgeyucel** [comment]
- [ ] Add API Keys to Github
- [ ] Mark some tutorials with `needs_gpu`

**Comment by silvanocerza** [comment]
Reopening as we still need to run tutorials on PRs.

**Comment by bilgeyucel** [comment]
Current TODOs for this issue:

```[tasklist]
### Tasks
- [ ] Test running on PRs with **latest 2.0 version** & **latest 1.x version** & **pinned versions** (for deprecated tutorials) 
- [ ] Nightly tests with **latest 2.0 version**
```
