### ISSUE TITLE
Replace usage of Generators with ChatGenerators in all tutorials

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-tutorials#356]
We should replace the usage of Generators with ChatGenerators in all tutorials so that users are prepared to use ChatGenerators in future and benefit from all future new features of ChatGenerators such as function calling, async, etc.

```[tasklist]
### Tasks
- [x] [27_First_RAG_Pipeline](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/27_First_RAG_Pipeline.ipynb). Code changes are drafted in [this notebook](https://colab.research.google.com/drive/1pgi2_hRe5-PPi8qsFeIaK9fKH2SZ4DAg?usp=sharing).
- [x] [28_Structured_Output_With_Loop](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/28_Structured_Output_With_Loop.ipynb)
- [x] [29_Serializing_Pipelines](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/29_Serializing_Pipelines.ipynb)
- [x] [30_File_Type_Preprocessing_Index_Pipeline](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/30_File_Type_Preprocessing_Index_Pipeline.ipynb)
- [x] [32_Classifying_Documents_and_Queries_by_Language](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/32_Classifying_Documents_and_Queries_by_Language.ipynb)
- [x] [35_Evaluating_RAG_Pipelines](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/35_Evaluating_RAG_Pipelines.ipynb)
- [x] [36_Building_Fallbacks_with_Conditional_Routing](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/36_Building_Fallbacks_with_Conditional_Routing.ipynb). Code changes are drafted in [this notebook](https://colab.research.google.com/drive/1L9BxyUmGOf4EDOSq2bkONmxRz7dKHva9?usp=sharing).
- [x] [37_Simplifying_Pipeline_Inputs_with_Multiplexer](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/37_Simplifying_Pipeline_Inputs_with_Multiplexer.ipynb). We should simply remove this tutorial because the Multiplexer component was removed in 2.4.0.
- [x] [40_Building_Chat_Application_with_Function_Calling](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/40_Building_Chat_Application_with_Function_Calling.ipynb)
```

Related issues:
* https://github.com/deepset-ai/haystack-tutorials/issues/349
* https://github.com/deepset-ai/haystack/issues/8410
* https://github.com/deepset-ai/haystack-tutorials/issues/350

**Comment by julian-risch** [comment]
Didn't work on this so I'll move it back to backlog.

**Comment by julian-risch** [comment]
Moving this issue back to backlog because of lack of time to work on it. We should also first merge the open PRs with ChatMessage changes.
